"""
cpf/vectors.py — Reference test vectors for CPF GateLock v1.

Each vector contains:
  - hyperloop_state: the exact state that was hashed
  - cpf_params: the exact params that were committed
  - gatelock: the built GateLock (minus sigset)
  - beacon_output_hex: the beacon value used
  - expected: { omega, x_fire_hex, t_fire_hex, fire }

If your implementation matches all expected values byte-for-byte,
you are cross-client compatible.

Generated by: python3 -m cpf.generate_vectors
"""
import hashlib

from cpf.canon import canon, h_obj, ledger_head_hash, params_commit
from cpf.beacon import canonical_b32, drand_round_for_time
from cpf.derive import derive, thresh, fire_decision
from cpf.gatelock import build_gatelock, build_round_result


# ---- Vector 1: R454 post-FIRE#115, poly_c=0.2249, no fire expected ----
V1_STATE = {
    "N": 535,
    "tau": 4,
    "omega": 2,
    "poly_c": 2249,          # stored as scaled integer * 10000 (human display)
    "round_id": 455,
    "fires": 115,
    "V": 16942995,           # V=16.942995 stored as int * 10^6
}

V1_PARAMS = {
    "poly_c_scaled": 224900000000000000,   # 0.2249 * 10^18
    "fire_function": "poly_c_threshold_v1",
    "clamp_min": 0,
    "clamp_max": 1000000000000000000,      # 10^18
    "omega_modulus": 3,
    "schema_version": "cpf_params_v1",
    "beacon_canon": "HASHED32",
}

# Deterministic: use a fixed lock_time for reproducibility
V1_LOCK_TIME_MS = 1772628000000   # 2026-03-04T13:00:00Z as unix ms
V1_ROUND_ID = 455
V1_LOCK_HEIGHT = 115              # fires count at lock time

# Synthetic beacon output (32 bytes = 64 hex chars, for testing)
# In production this comes from drand/chainlink after beacon_target
V1_BEACON_HEX = "a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4"


def generate_v1() -> dict:
    """Generate Vector 1 and return all intermediate values."""
    lhh = ledger_head_hash(V1_STATE)
    pc  = params_commit(V1_PARAMS)
    gate = build_gatelock(
        round_id=V1_ROUND_ID,
        lock_height=V1_LOCK_HEIGHT,
        hyperloop_state=V1_STATE,
        cpf_params=V1_PARAMS,
        beacon_id="drand-mainnet",
        lock_time_unix_ms=V1_LOCK_TIME_MS,
        window_id="run44:R455",
    )
    result = build_round_result(
        round_id=V1_ROUND_ID,
        gate=gate,
        beacon_output_hex=V1_BEACON_HEX,
        hyperloop_state=V1_STATE,
        cpf_params=V1_PARAMS,
    )
    return {
        "vector_id": "cpf_v1_R455_nofire",
        "description": "R455, N=535, tau=4, omega=2, poly_c=0.2249 — no fire expected",
        "hyperloop_state": V1_STATE,
        "cpf_params": V1_PARAMS,
        "ledger_head_hash": lhh,
        "params_commit": pc,
        "gatelock": gate,
        "beacon_output_hex": V1_BEACON_HEX,
        "result": result,
    }


# ---- Vector 2: high poly_c, fire expected ----
V2_STATE = {
    "N": 534,
    "tau": 8,
    "omega": 3,
    "poly_c": 7516,          # 0.7516
    "round_id": 454,
    "fires": 114,
    "V": 16942995,
}

V2_PARAMS = {
    "poly_c_scaled": 751600000000000000,  # 0.7516 * 10^18
    "fire_function": "poly_c_threshold_v1",
    "clamp_min": 0,
    "clamp_max": 1000000000000000000,
    "omega_modulus": 3,
    "schema_version": "cpf_params_v1",
    "beacon_canon": "HASHED32",
}

V2_LOCK_TIME_MS = 1772625600000   # 2026-03-04T12:20:00Z
V2_ROUND_ID = 454
V2_LOCK_HEIGHT = 114
V2_BEACON_HEX = "f1e2d3c4b5a6978869504132231415161718192021222324252627282930313233"


def generate_v2() -> dict:
    lhh = ledger_head_hash(V2_STATE)
    pc  = params_commit(V2_PARAMS)
    gate = build_gatelock(
        round_id=V2_ROUND_ID,
        lock_height=V2_LOCK_HEIGHT,
        hyperloop_state=V2_STATE,
        cpf_params=V2_PARAMS,
        beacon_id="drand-mainnet",
        lock_time_unix_ms=V2_LOCK_TIME_MS,
        window_id="run43:R454",
    )
    result = build_round_result(
        round_id=V2_ROUND_ID,
        gate=gate,
        beacon_output_hex=V2_BEACON_HEX,
        hyperloop_state=V2_STATE,
        cpf_params=V2_PARAMS,
    )
    return {
        "vector_id": "cpf_v1_R454_fire",
        "description": "R454, N=534, tau=8, omega=3, poly_c=0.7516 — fire expected when x_fire < t_fire",
        "hyperloop_state": V2_STATE,
        "cpf_params": V2_PARAMS,
        "ledger_head_hash": lhh,
        "params_commit": pc,
        "gatelock": gate,
        "beacon_output_hex": V2_BEACON_HEX,
        "result": result,
    }


def run_all() -> dict:
    v1 = generate_v1()
    v2 = generate_v2()
    return {"vectors": [v1, v2]}


if __name__ == "__main__":
    import json
    out = run_all()
    print(json.dumps(out, indent=2))
